# This is a basic workflow that is manually triggered

name: Merge AD List
on:
  push:
    branches: [ "main" ]
    paths: [ "filter/**","mobile/**","/.github/workflows/adlist.yml" ]
  workflow_dispatch: ~
jobs:
  Merge:
    runs-on: ubuntu-latest
    steps:
    - name: set beijing timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Shanghai"
    - name: Checkout
      uses: actions/checkout@master
    - name: Generate block list(pc)
      run: |
        cat filter/00head.info > list.txt
        sed -i "2i\! Version: $(date +'%Y%m%d%H%M')" list.txt
        awk '{print}' filter/*.txt | grep -v '^!' >> list.txt
    - name: Generate block list(mobile)
      run: |
        cat mobile/00head.info > mlist.txt
        sed -i "2i\! Version: $(date +'%Y%m%d%H%M')" mlist.txt
        awk '{print}' mobile/*.txt | grep -v '^!' >> mlist.txt
    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1.4
      with:
        author_name: kimi360
        author_email: kimi360@gamil.com
        message: "更新过滤列表"
        add: '["list.txt","mlist.txt"]'
    - name: Send Webhook
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        headers: '{"Accept": "application/vnd.github.everest-preview+json", "Authorization": "token ${{ secrets.WEBHOOK_TOKEN }}"}'
        body: '{"event_type": "webhook"}'
