# This is a basic workflow that is manually triggered

name: Merge List
on:
  push:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Send greeting
      run: cat filter/*.txt > list.txt && cat list.txt
